# Generated by Django 4.0.3 on 2022-03-04 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_state', models.CharField(max_length=200)),
                ('current_state', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamHunt.robot')),
            ],
        ),
    ]
