# Generated by Django 3.2.9 on 2022-03-04 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TeamHunt', '0002_delete_message_delete_robot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=200)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamHunt.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('previous_state', models.CharField(max_length=200)),
                ('current_state', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=200)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamHunt.coach')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TeamHunt.robot')),
            ],
        ),
    ]
